#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: tracing-server
#  namespace: petclinic-dev
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: tracing-server
#  template:
#    metadata:
#      labels:
#        app: tracing-server
#    spec:
#      containers:
#        - name: tracing-server
#          image: openzipkin/zipkin
#          resources:
#            limits:
#              memory: 512Mi
#          ports:
#            - containerPort: 9411
