apiVersion: v1
kind: Service
metadata:
  name: tracing-server
  namespace: petclinic-dev
spec:
  selector:
    app: tracing-server
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
  type: ClusterIP 
