apiVersion: v1
kind: Service
metadata:
  name: petclinic-discovery-server-service
  namespace: petclinic-staging
spec:
  type: NodePort   
  selector:
    app: petclinic-discovery-server
  ports:
    - name: tcp
      port: 8761         
      targetPort: 8761    
      nodePort: 30061    
  sessionAffinity: None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
