#apiVersion: v1
#kind: Service
#metadata:
#  name: petclinic-customers-service-service
#  namespace: petclinic-dev
#spec:
#  type: NodePort   
#  selector:
#    app: petclinic-customers-service
#  ports:
#    - name: tcp
#      port: 8081         
#      targetPort: 8081    
#      nodePort: 30081    