
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic-config-server
  name: petclinic-config-server-deployment
  namespace: petclinic-staging
spec:
  replicas: 1
  revisionHistoryLimit: 11
  selector:
    matchLabels:
      app: petclinic-config-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: petclinic-config-server
      namespace: petclinic-staging
    spec:
      containers:
        - image: thuanlp/spring-petclinic-config-server:latest
          imagePullPolicy: Always
          name: petclinic-config-server
          ports:
            - containerPort: 8888
              name: tcp
              protocol: TCP
          resources:
            requests:
              memory: "400Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "800m"
          volumeMounts:
            - mountPath: /app/src/main/resources/application.properties
              name: petclinic-config-server-application-properties-config-volume
              subPath: application.properties
      imagePullSecrets:
      - name: dockerhub
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: petclinic-config-server-application-properties-configmap
          name: petclinic-config-server-application-properties-config-volume
          
