apiVersion: v1
kind: Service
metadata:
  name: petclinic-config-server-service
  namespace: petclinic-staging
spec:
  type: NodePort   
  selector:
    app: petclinic-config-server
  ports:
    - name: tcp
      port: 8888         
      targetPort: 8888    
      nodePort: 30088     
  sessionAffinity: None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
