apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-vets-service-application-properties-configmap
  namespace: petclinic-dev
data:
  application.properties: |
    spring.application.name=vets-service
    spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://petclinic-config-server-service:8888/}
    spring.cache.cache-names=vets
