apiVersion: v1
kind: Service
metadata:
  name: petclinic-vets-service-service
  namespace: petclinic-dev
spec:
  type: NodePort   
  selector:
    app: petclinic-vets-service
  ports:
    - name: tcp
      port: 8083         
      targetPort: 8083    
      nodePort: 30083  