#apiVersion: v1
#kind: Service
#metadata:
#  name: petclinic-visits-service-service
#  namespace: petclinic-dev
#spec:
#  type: NodePort   
#  selector:
#    app: petclinic-visits-service
#  ports:
#    - name: tcp
#      port: 8082         
#      targetPort: 8082    
#      nodePort: 30082 