#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: petclinic-api-gateway-application-properties-configmap
#  namespace: petclinic-dev
#data:
#  application.properties: |
#    spring.application.name=api-gateway
#    spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://petclinic-config-server-service:8888/}
#    
#    spring.cloud.gateway.default-filters[0].name=CircuitBreaker
#    spring.cloud.gateway.default-filters[0].args.name=defaultCircuitBreaker
#    spring.cloud.gateway.default-filters[0].args.fallbackUri=forward:/fallback
#    
#    spring.cloud.gateway.default-filters[1].name=Retry
#    spring.cloud.gateway.default-filters[1].args.retries=1
#    spring.cloud.gateway.default-filters[1].args.statuses=SERVICE_UNAVAILABLE
#    spring.cloud.gateway.default-filters[1].args.methods=POST
#    
#    spring.cloud.gateway.routes[0].id=vets-service
#    spring.cloud.gateway.routes[0].uri=http://petclinic-vets-service-service:8083
#    spring.cloud.gateway.routes[0].predicates[0]=Path=/api/vet/**
#    spring.cloud.gateway.routes[0].filters[0]=StripPrefix=2
#    
#    spring.cloud.gateway.routes[1].id=visits-service
#    spring.cloud.gateway.routes[1].uri=http://petclinic-visits-service-service:8082
#    spring.cloud.gateway.routes[1].predicates[0]=Path=/api/visit/**
#    spring.cloud.gateway.routes[1].filters[0]=StripPrefix=2
#    
#    spring.cloud.gateway.routes[2].id=customers-service
#    spring.cloud.gateway.routes[2].uri=http://petclinic-customers-service-service:8081
#    spring.cloud.gateway.routes[2].predicates[0]=Path=/api/customer/**
#    spring.cloud.gateway.routes[2].filters[0]=StripPrefix=2
#    
#    spring.cloud.gateway.routes[3].id=genai-service
#    spring.cloud.gateway.routes[3].uri=http://petclinic-genai-service-service:8084
#    spring.cloud.gateway.routes[3].predicates[0]=Path=/api/genai/**
#    spring.cloud.gateway.routes[3].filters[0]=StripPrefix=2
#    spring.cloud.gateway.routes[3].filters[1]=CircuitBreaker=name=genaiCircuitBreaker,fallbackUri=/fallback