apiVersion: v1
kind: Service
metadata:
  name: petclinic-api-gateway-service
  namespace: petclinic-dev
spec:
  type: NodePort   
  selector:
    app: petclinic-api-gateway
  ports:
    - name: tcp
      port: 8080         
      targetPort: 8080    
      nodePort: 30089    
