apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-customers-service-application-properties-configmap
  namespace: petclinic-staging
data:
  application.properties: |
    spring.application.name=customers-service
    spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://petclinic-config-server-service:8888/}
