#apiVersion: v1
#kind: Service
#metadata:
#  name: petclinic-genai-service-service
#  namespace: petclinic-dev
#spec:
#  type: NodePort   
#  selector:
#    app: petclinic-genai-service
#  ports:
#    - name: tcp
#      port: 8084         
#      targetPort: 8084    
#      nodePort: 30084  