apiVersion: v1
kind: Service
metadata:
  name: petclinic-vets-service-service
  namespace: petclinic-staging
spec:
  type: NodePort   
  selector:
    app: petclinic-vets-service
  ports:
    - name: tcp
      port: 8083         
      targetPort: 8083    
      nodePort: 30083  
  sessionAffinity: None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
