apiVersion: v1
kind: Service
metadata:
  name: petclinic-genai-service-service
  namespace: petclinic-staging
spec:
  type: NodePort   
  selector:
    app: petclinic-genai-service
  ports:
    - name: tcp
      port: 8084         
      targetPort: 8084    
      nodePort: 30084  
  sessionAffinity: None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
