#apiVersion: v1
#kind: Service
#metadata:
#  name: petclinic-admin-server-service
#  namespace: petclinic-dev
#spec:
#  type: NodePort   
#  selector:
#    app: petclinic-admin-server
#  ports:
#    - name: tcp
#      port: 9090         
#      targetPort: 9090    
#      nodePort: 30090     
